[build]
  publish = "video-hls/iremderici-bentek"

[[headers]]
  for = "/*.m3u8"
  [headers.values]
    Content-Type = "application/vnd.apple.mpegurl"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "video/mp2t"
